# Generated by Django 4.1.7 on 2023-04-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemesan', models.CharField(max_length=200)),
                ('alamat_penerima', models.CharField(max_length=200)),
                ('penerima', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kurir',
            fields=[
                ('id_kurir', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('area_pengiriman', models.CharField(max_length=200)),
            ],
        ),
    ]
