# Generated by Django 4.1.7 on 2023-04-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('resi', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('namaPenerima', models.CharField(max_length=20)),
                ('noHpPenerima', models.IntegerField(default=12)),
                ('alamat', models.TextField(max_length=100)),
                ('nominalCOD', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='noHp',
            field=models.IntegerField(default=12),
        ),
    ]
