# Generated by Django 4.1.7 on 2023-04-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_paket_users_nohp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_admin', models.CharField(max_length=50)),
                ('id_admin', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_barang', models.CharField(max_length=10, unique=True)),
                ('status_barang', models.CharField(choices=[('POS', 'Gagal Dikirim'), ('POD', 'Sukses Dikirim')], default='POD', max_length=3)),
                ('nama_penerima', models.CharField(max_length=50)),
                ('tujuan', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Kurir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kurir', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('no_telepon', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.CharField(max_length=10, unique=True)),
                ('waktu_pos', models.DateTimeField(blank=True, null=True)),
                ('waktu_pod', models.DateTimeField(blank=True, null=True)),
                ('bukti_pos', models.ImageField(blank=True, null=True, upload_to='bukti_pos/')),
                ('bukti_pod', models.ImageField(blank=True, null=True, upload_to='bukti_pod/')),
                ('jml_paket_pos', models.PositiveIntegerField(blank=True, null=True)),
                ('jml_paket_pod', models.PositiveIntegerField(blank=True, null=True)),
                ('barang', models.ManyToManyField(to='app.barang')),
                ('kurir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kurir')),
            ],
        ),
        migrations.DeleteModel(
            name='Paket',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
