# Generated by Django 4.1.7 on 2023-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_admin_barang_kurir_taskdelivery_delete_paket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='id_barang',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='kurir',
            name='no_telepon',
            field=models.CharField(max_length=12),
        ),
    ]
