# Generated by Django 4.1.7 on 2023-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_barang_id_barang_alter_kurir_no_telepon'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurir',
            name='area_pengiriman',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
