# Generated by Django 4.1.7 on 2023-04-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_kurir_area_pengiriman'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='nama_pemesan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
