# Generated by Django 4.1.7 on 2023-04-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_barang_nama_pemesan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdelivery',
            old_name='kurir',
            new_name='id_kurir',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='id_admin',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='nama_admin',
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='userid',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taskdelivery',
            name='waktu_pod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskdelivery',
            name='waktu_pos',
            field=models.DateField(blank=True, null=True),
        ),
    ]
