# Generated by Django 4.1.7 on 2023-04-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_kurir_taskdelivery_id_kurir_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='userid',
            new_name='id_Amin',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='username',
            new_name='nama_admin',
        ),
    ]
