# Generated by Django 4.1.7 on 2023-05-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_barang_taskdelivery_id_barang_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdelivery',
            old_name='id_barang',
            new_name='barang',
        ),
    ]
