# Generated by Django 4.1.7 on 2023-05-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_id_barang_taskdelivery_barang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='id_admin',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='nama_admin',
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
