# Generated by Django 4.1.7 on 2023-05-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RenameField(
            model_name='taskdelivery',
            old_name='barang',
            new_name='id_barang',
        ),
    ]
