# Generated by Django 4.1.7 on 2023-05-25 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdelivery',
            name='id_barang',
        ),
        migrations.AddField(
            model_name='taskdelivery',
            name='id_barang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.barang'),
        ),
    ]
